export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS"

export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
